Repository European-XFEL/EXtra, pull requests merged in 2024-11, with the labels that each got.

#260 Relax contourpy dependecy to avoid version conflicts
  .github/dependabot/constraints.txt
Labels: dependencies

#258 Fix missing chapter link for Timepix component
  mkdocs.yml
Labels: skip-changelog

#262 Allow passing a figure size to Scan.plot()
  docs/changelog.md
  src/extra/components/scan.py
Labels: enhancement
