Repository European-XFEL/EXtra, pull requests merged in 2024-03, with the labels that each got.

#127 Store & access all CCV metadata from CalCat
  src/extra/calibration.py
  tests/test_calibration.py
Labels: enhancement

#140 Add job to publish packages on PyPI when a tag passes tests
  .github/workflows/tests.yml
Labels: skip-changelog

#143 Prepare changelog for 2024.1.1
  docs/changelog.md
Labels: documentation

#144 Update Github actions to fix warnings about Node.js 16
  .github/workflows/tests.yml
Labels: skip-changelog

#147 Mask all non-finite values in fit_gaussian()
  src/extra/utils/functions.py
  tests/test_utils.py
Labels: bug, skip-changelog
