Repository European-XFEL/EXtra, pull requests merged in 2024-09, with the labels that each got.

#227 Fix sign for stage-to-time conversion in OpticalLaserDelay
  src/extra/components/las.py
Labels: skip-changelog

#232 Move XGM mock devices to their own module in .mockdata
  tests/conftest.py
  tests/mockdata/xgm.py
Labels: skip-changelog

#237 Actually use title/xlabel/ylabel in Scan.plot_bin_by_steps()
  docs/changelog.md
  src/extra/components/scan.py
Labels: bug

#236 Fix initializing PumpProbePulses with an instrument string
  src/extra/components/_common.py
  src/extra/components/las.py
  src/extra/components/pulses.py
  src/extra/components/utils.py
  tests/test_components_pulses.py
  tests/test_components_util.py
Labels: skip-changelog

#222 Add A_sign parameter for fit_gaussian()
  docs/changelog.md
  src/extra/utils/functions.py
  tests/test_utils.py
Labels: enhancement

#242 Improve extrapolation exceptions in PumpProbePulses
  src/extra/components/pulses.py
  tests/test_components_pulses.py
Labels: skip-changelog
