Repository European-XFEL/EXtra, pull requests merged in 2025-07, with the labels that each got.

#332 Align pulse information to the ADQ trains before using them
  src/extra/components/adq.py
  tests/test_components_adq.py
Labels: skip-changelog

#347 Use nans instead of zeros as a fill value in XGM.pulse_energy()
  docs/changelog.md
  src/extra/components/xgm.py
Labels: bug

#353 Add a stub for extra-proposal
  pyproject.toml
  src/extra/proposal/__init__.py
Labels: enhancement, skip-changelog

#359 Remove the TOF*Response recipes from the docs
  docs/changelog.md
  docs/recipes/index.md
  mkdocs.yml
Labels: skip-changelog

#361 Fix pulse alignment when retrieving train and pulse edges
  src/extra/components/adq.py
  tests/test_components_adq.py
Labels: skip-changelog

#358 Update the install-extra.sh script for pixi
  README.md
  docs/install-extra.sh
Labels: skip-changelog
