Repository European-XFEL/EXtra, pull requests merged in 2025-04, with the labels that each got.

#312 Use _reshape_flat_pulses rather than _reshape_pulses_by_train for pulse splitting
  docs/changelog.md
  src/extra/components/adq.py
Labels: skip-changelog

#319 Delete nonexistent arguments from a docstring
  .github/dependabot/constraints.txt
  src/extra/recipes/grating.py
Labels: documentation, skip-changelog

#325 Update changelog
  docs/changelog.md
Labels: documentation

#316 Add tests to ADQ component for actual data retrieval
  src/extra/__init__.py
  src/extra/components/adq.py
  tests/test_components_adq.py
Labels: skip-changelog
