Repository European-XFEL/EXtra, pull requests merged in 2025-06, with the labels that each got.

#334 Always use the passed axis in Scan.plot_bin_by_steps()
  docs/changelog.md
  src/extra/components/scan.py
Labels: bug

#337 Update EXtra-data & EXtra-geom to latest versions on CI
  .github/dependabot/constraints.txt
Labels: dependencies

#330 Allow building with Cython 3.1.2
  pyproject.toml
Labels: dependencies

#345 Fix XGM.plot_pulse_energy() to not show an extra colorbar
  src/extra/components/xgm.py
  tests/test_components_xgm.py
Labels: bug, skip-changelog

#348 Implement hyperslicer2() for plotting image arrays
  docs/changelog.md
  docs/images/hyperslicer2.gif
  docs/utilities.md
  mkdocs.yml
  pyproject.toml
  src/extra/utils/misc.py
  tests/test_utils.py
Labels: enhancement

#349 Add reorder_axes_to_shape function
  docs/changelog.md
  docs/utilities.md
  src/extra/components/utils.py
  src/extra/utils/misc.py
  tests/test_utils.py
Labels: enhancement
